### ISSUE TITLE
Rusoku TouCAN Marine device

### ISSUE THREAD

**Issue by gedass2000** [TwoCanPlugIn/TwoCanPlugIn#11]
how to enable Rusoku TouCAN Marine device in twocan plugin v.1.9 (OpenCPN 5.2.0) ? It isn't in the device list by default.

**Comment by gedass2000** [comment]
Seems like toucan.dll is not added to twocan plugin driver list in ver.1.9

**Comment by TwoCanPlugIn** [comment]
Hi Gediminas,

Will try and do this in the next major release. My problem is understanding how to install the correct toucan.dll for Windows 7, Windows 8 & Windows 10 in both 32 & 64 bit versions. The problem is exacerbated because the new OpenCPN 5.2 Plugin Manager just uses a metadata file & tarball to install the plugin, and there is no installer available to determine which toucan.dll to install.

Thanks.

**Comment by gedass2000** [comment]
Hi Steve,
imho toucan driver should be installed like Kvaser Light driver.OpenCPN driver part toucan.dll to OpenCPN twocan plugin place and additional installation canal32.dll drivers from Rusoku site.
I still no have idea why OpenCPN doesn't find canal32.dll library in Windows\System32\ directory.Only in OpenCPN main directory when CanalView software can find.
Next step imho is to rewrite twocan toucan.dll library to operate without canal.dll library. From one side OpenCPN plugin and from another - WinUSB library.
BTW tocan.dll has a bug .It crashes without attached real TouCAN converter hardware.I will check a code this weekend.
